export const TRAIT_LABELS = {
  realistic: "Realistic",
  investigative: "Investigative",
  artistic: "Artistic",
  social: "Social",
  enterprising: "Enterprising",
  conventional: "Conventional",
  openness: "Openness",
  conscientiousness: "Conscientiousness",
  extraversion: "Extraversion",
  agreeableness: "Agreeableness",
  stability: "Emotional Stability",
  analytical: "Analytical",
  communication: "Communication",
  numerical: "Numerical",
  spatial: "Spatial",
  interpersonal: "Interpersonal",
  technical: "Technical",
  leadership: "Leadership",
  creative: "Creative",
  organizational: "Organizational",
  attentionToDetail: "Attention to Detail",
  achievement: "Achievement",
  independence: "Independence",
  recognition: "Recognition",
  relationships: "Relationships",
  comfort: "Comfort",
  altruism: "Altruism",
  security: "Security",
  variety: "Variety",
};
